services:
  # --- Banco de Dados Postgres ---
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "2542"
      POSTGRES_DB: usuario
    ports:
      - "5433:5432"

  # --- Banco de Dados MongoDB ---
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: db_agendador
    ports:
      - "27017:27017"

  # --- Microsserviço: Usuario ---
  usuario:
    build: ../usuario
    container_name: usuario
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/usuario
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2542
    depends_on:
      - postgres

  # --- Microsserviço: Agendador de Tarefas ---
  agendador-tarefas:
    build: ../agendador-tarefas
    container_name: agendador-tarefas
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/db_agendador
    depends_on:
      - mongo

  # --- Microsserviço: Notificação ---
  notificacao:
    build: ../notificacao
    container_name: notificacao
    ports:
      - "8084:8084"

  # --- BFF (Backend For Frontend) ---
  bff-agendador-tarefas:
    build: .
    container_name: bff-agendador-tarefas
    ports:
      - "8083:8083"
    environment:
      - USUARIO_URL=http://usuario:8080/usuario
      - AGENDADOR_TAREFAS_URL=http://agendador-tarefas:8081/tarefas
      - NOTIFICACAO_URL=http://notificacao:8082/email
    depends_on:
      - usuario
      - agendador-tarefas
      - notificacao

networks:
  default:
    driver: bridge